package z:eth-agent@0.1.0;

world eth-agent {
  export contracts;
}

interface contracts {
  record generic-input {
    input:        option<list<u8>>,
    user-profile: option<list<u8>>,
    context:      option<list<u8>>,
  }

  check-policy:     func(req: generic-input) -> result<list<u8>, string>;
  execute-transfer: func(req: generic-input) -> result<list<u8>, string>;
  get-balance:      func(req: generic-input) -> result<list<u8>, string>;
  queue-action:     func(req: generic-input) -> result<list<u8>, string>;
  enroll-employee:  func(req: generic-input) -> result<list<u8>, string>;
  verify-employee:  func(req: generic-input) -> result<list<u8>, string>;
  process-payroll:  func(req: generic-input) -> result<list<u8>, string>;
}
